AppBundle\Entity\Product:
    type: entity
    table: product
    indexes:
        category_id:
            columns:
                - category_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        categoryId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: category_id
    lifecycleCallbacks: {  }
